// <auto-generated />
namespace ProjectTest2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class U11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(U11));
        
        string IMigrationMetadata.Id
        {
            get { return "201611180956367_U11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
